baseURL = "http://getfider.com/"
languageCode = "en-us"
title = "Fider"
theme = "kube"
publishDir = "docs"
description = "Fider is a platform to share ideas and collect customer feedback"
googleAnalytics = "UA-100812395-1"
[Params]
  RSSLink = "/index.xml"
  author = "Fider" # add your company name
  email = "me@goenning.net"
  images = [ "images/logo-small.png" ]

 [[menu.main]]
   name = "Docs"
   weight = -100
   url = "/docs/"
 [[menu.main]]
   name = "Blog"
   weight = -100
   url = "/blog/"
# [[menu.main]]
#   name = "Faq"
#   weight = -100
#   url = "/faq/"
