baseURL = "/"
languageCode = "en-us"
title = "Fider"
theme = "kube"
publishDir = "docs"
description = "Fider is an open source, cross platform and free to use customer feedback system for companies and products"
googleAnalytics = "UA-100812395-1"
[Params]
  RSSLink = "/index.xml"
  author = "Fider" # add your company name
  email = "me@goenning.net"

 [[menu.main]]
   name = "Docs"
   weight = -100
   url = "/docs/"
 [[menu.main]]
   name = "Blog"
   weight = -100
   url = "/blog/"
# [[menu.main]]
#   name = "Faq"
#   weight = -100
#   url = "/faq/"
