baseURL = "https://getfider.com/"
title = "Fider"
publishDir = "docs"
description = "Open platform to collect and organize product feedback"
googleAnalytics = "UA-100812395-1"
[Params]
  RSSLink = "/index.xml"
  author = "Fider"
  email = "admin@fider.io"
  images = [ "images/logo-small.png" ]

 [[menu.main]]
   name = "Blog"
   weight = 100
   url = "/blog"

 [[menu.main]]
   name = "Docs"
   weight = 200
   url = "/docs"

 [[menu.main]]
   name = "About"
   weight = 300
   url = "/about"

 [[menu.footer]]
   name = "About"
   weight = 100
   url = "/about"

 [[menu.footer]]
   name = "Blog"
   weight = 200
   url = "/blog"

 [[menu.footer]]
   name = "Docs"
   weight = 300
   url = "/docs"

 [[menu.footer]]
   name = "Status"
   weight = 400
   url = "https://status.fider.io/"

 [[menu.footer]]
   name = "GitHub"
   weight = 500
   url = "https://github.com/getfider/fider"